// lib/seed-artworks.ts
// Fallback seed artworks shown when Supabase DB is empty.
// Replace with live DB data by running ingestion from /admin.

export const SEED_ARTWORKS = [
  {
    id: 'seed-1',
    title: 'Mona Lisa',
    year: 'c. 1503–1519',
    year_start: 1503,
    year_end: 1519,
    region: 'Europe',
    culture: 'Italian',
    medium: 'Oil on poplar panel',
    lat: 43.769562,
    lng: 11.255814,
    image_url: null,
    description: 'Half-length portrait painting by Leonardo da Vinci, considered the greatest work of the Renaissance master.',
    current_museum: 'Louvre Museum, Paris',
    place_created: 'Florence, Italy',
    tags: ['Renaissance', 'Portrait', 'Italian'],
  },
  {
    id: 'seed-2',
    title: 'The Starry Night',
    year: '1889',
    year_start: 1889,
    year_end: 1889,
    region: 'Europe',
    culture: 'Dutch',
    medium: 'Oil on canvas',
    lat: 52.370216,
    lng: 4.895168,
    image_url: null,
    description: 'A swirling night sky over a village, painted by Vincent van Gogh from his room at the asylum in Saint-Rémy.',
    current_museum: 'MoMA, New York',
    place_created: 'Saint-Rémy-de-Provence, France',
    tags: ['Post-Impressionism', 'Landscape', 'Dutch'],
  },
  {
    id: 'seed-3',
    title: 'The Great Wave off Kanagawa',
    year: 'c. 1831',
    year_start: 1830,
    year_end: 1833,
    region: 'Asia',
    culture: 'Japanese',
    medium: 'Woodblock print (nishiki-e)',
    lat: 35.6762,
    lng: 139.6503,
    image_url: null,
    description: 'Iconic woodblock print by Hokusai from the Thirty-six Views of Mount Fuji series.',
    current_museum: 'Metropolitan Museum of Art',
    place_created: 'Edo (Tokyo), Japan',
    tags: ['Ukiyo-e', 'Japanese', 'Seascape'],
  },
  {
    id: 'seed-4',
    title: 'Girl with a Pearl Earring',
    year: 'c. 1665',
    year_start: 1665,
    year_end: 1665,
    region: 'Europe',
    culture: 'Dutch',
    medium: 'Oil on canvas',
    lat: 52.0809,
    lng: 4.3133,
    image_url: null,
    description: 'A tronie painting by Johannes Vermeer, often called the "Mona Lisa of the North".',
    current_museum: 'Mauritshuis, The Hague',
    place_created: 'Delft, Netherlands',
    tags: ['Dutch Golden Age', 'Portrait', 'Dutch'],
  },
  {
    id: 'seed-5',
    title: 'The Birth of Venus',
    year: 'c. 1484–1486',
    year_start: 1484,
    year_end: 1486,
    region: 'Europe',
    culture: 'Italian',
    medium: 'Tempera on canvas',
    lat: 43.7680,
    lng: 11.2560,
    image_url: null,
    description: 'Sandro Botticelli\'s masterpiece depicting the goddess Venus emerging fully-formed from the sea.',
    current_museum: 'Uffizi Gallery, Florence',
    place_created: 'Florence, Italy',
    tags: ['Renaissance', 'Mythology', 'Italian'],
  },
  {
    id: 'seed-6',
    title: 'Guernica',
    year: '1937',
    year_start: 1937,
    year_end: 1937,
    region: 'Europe',
    culture: 'Spanish',
    medium: 'Oil on canvas',
    lat: 40.4068,
    lng: -3.6938,
    image_url: null,
    description: 'Pablo Picasso\'s powerful anti-war statement depicting the Nazi German bombing of the Basque town of Guernica.',
    current_museum: 'Museo Reina Sofía, Madrid',
    place_created: 'Paris, France',
    tags: ['Cubism', 'Anti-war', 'Spanish'],
  },
  {
    id: 'seed-7',
    title: 'The Night Watch',
    year: '1642',
    year_start: 1642,
    year_end: 1642,
    region: 'Europe',
    culture: 'Dutch',
    medium: 'Oil on canvas',
    lat: 52.3600,
    lng: 4.8852,
    image_url: null,
    description: 'Rembrandt\'s massive group portrait of a militia company, one of the most celebrated paintings in the Dutch Golden Age.',
    current_museum: 'Rijksmuseum, Amsterdam',
    place_created: 'Amsterdam, Netherlands',
    tags: ['Dutch Golden Age', 'Portrait', 'Baroque'],
  },
  {
    id: 'seed-8',
    title: 'Death Mask of Tutankhamun',
    year: 'c. 1323 BCE',
    year_start: -1323,
    year_end: -1323,
    region: 'Africa',
    culture: 'Egyptian',
    medium: 'Gold, lapis lazuli, carnelian, glass',
    lat: 25.7300,
    lng: 32.6100,
    image_url: null,
    description: 'The solid gold funerary mask of the Egyptian pharaoh Tutankhamun, discovered in 1922.',
    current_museum: 'Egyptian Museum, Cairo',
    place_created: 'Thebes (Luxor), Egypt',
    tags: ['Ancient Egypt', 'Gold', 'Funerary Art'],
  },
  {
    id: 'seed-9',
    title: 'Standing Bodhisattva',
    year: 'c. 100–200 CE',
    year_start: 100,
    year_end: 200,
    region: 'Asia',
    culture: 'Gandharan',
    medium: 'Schist',
    lat: 34.5210,
    lng: 69.1783,
    image_url: null,
    description: 'A Gandharan sculpture blending Hellenistic and Indian artistic traditions, depicting a Buddhist spiritual being.',
    current_museum: 'Metropolitan Museum of Art',
    place_created: 'Gandhara (modern Afghanistan/Pakistan)',
    tags: ['Buddhist', 'Gandharan', 'Sculpture'],
  },
  {
    id: 'seed-10',
    title: 'Bowl with Kufic Inscription',
    year: 'c. 9th–10th century',
    year_start: 850,
    year_end: 999,
    region: 'Middle East',
    culture: 'Samanid',
    medium: 'Slip-painted earthenware',
    lat: 35.6892,
    lng: 51.3890,
    image_url: null,
    description: 'Persian ceramic bowl with elegant Kufic calligraphy from the Samanid dynasty.',
    current_museum: 'Metropolitan Museum of Art',
    place_created: 'Nishapur, Iran',
    tags: ['Islamic', 'Ceramics', 'Persian'],
  },
  {
    id: 'seed-11',
    title: 'Terracotta Warrior',
    year: 'c. 210 BCE',
    year_start: -221,
    year_end: -206,
    region: 'Asia',
    culture: 'Chinese',
    medium: 'Painted terracotta',
    lat: 34.3847,
    lng: 109.2733,
    image_url: null,
    description: 'One of the thousands of life-sized clay soldiers in the burial army of China\'s first emperor Qin Shi Huang.',
    current_museum: 'Museum of the Terracotta Warriors, Xi\'an',
    place_created: "Xi'an, Shaanxi, China",
    tags: ['Ancient China', 'Qin Dynasty', 'Sculpture'],
  },
  {
    id: 'seed-12',
    title: 'The Ambassadors',
    year: '1533',
    year_start: 1533,
    year_end: 1533,
    region: 'Europe',
    culture: 'German',
    medium: 'Oil on oak',
    lat: 51.5074,
    lng: -0.1278,
    image_url: null,
    description: 'Hans Holbein\'s double portrait of two learned men, famous for its anamorphic skull at the bottom.',
    current_museum: 'National Gallery, London',
    place_created: 'London, England',
    tags: ['Northern Renaissance', 'Portrait', 'German'],
  },
  {
    id: 'seed-13',
    title: 'Seated Scribe',
    year: 'c. 2620–2500 BCE',
    year_start: -2620,
    year_end: -2500,
    region: 'Africa',
    culture: 'Egyptian',
    medium: 'Painted limestone',
    lat: 29.9792,
    lng: 31.1342,
    image_url: null,
    description: 'Remarkable ancient Egyptian statue of a cross-legged scribe with individualized, lifelike features.',
    current_museum: 'Louvre Museum, Paris',
    place_created: 'Memphis (Saqqara), Egypt',
    tags: ['Ancient Egypt', 'Sculpture', 'Old Kingdom'],
  },
  {
    id: 'seed-14',
    title: 'Katsushika Hokusai: Fine Wind, Clear Morning',
    year: 'c. 1830–1831',
    year_start: 1830,
    year_end: 1831,
    region: 'Asia',
    culture: 'Japanese',
    medium: 'Color woodblock print',
    lat: 35.3628,
    lng: 138.7307,
    image_url: null,
    description: 'Also known as Red Fuji — Mount Fuji bathed in morning light from the Thirty-six Views series.',
    current_museum: 'Metropolitan Museum of Art',
    place_created: 'Edo (Tokyo), Japan',
    tags: ['Ukiyo-e', 'Japanese', 'Landscape'],
  },
  {
    id: 'seed-15',
    title: 'Portrait of Emperor Jahangir',
    year: 'c. 1620',
    year_start: 1615,
    year_end: 1625,
    region: 'Asia',
    culture: 'Mughal',
    medium: 'Opaque watercolor and gold on paper',
    lat: 28.6139,
    lng: 77.2090,
    image_url: null,
    description: 'An opulent Mughal miniature portrait showing Emperor Jahangir surrounded by symbolic imagery.',
    current_museum: 'Freer Gallery, Washington D.C.',
    place_created: 'Agra, India',
    tags: ['Mughal', 'Indian', 'Miniature'],
  },
];
